"""Recompute the progress block in ROADMAP.md from its checkboxes.

Usage:  venv/Scripts/python.exe scripts/roadmap_progress.py [--check]

Counts ``- [x]`` as 1, ``- [~]`` as 0.5 and ``- [ ]`` as 0 inside every
``## Week N`` section, then rewrites the text between the
``<!-- progress:start -->`` and ``<!-- progress:end -->`` markers. Weeks with no
checkbox yet count as 0 %. ``--check`` exits 1 if the block is out of date
(useful as a pre-commit guard).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROADMAP = Path(__file__).resolve().parent.parent / "ROADMAP.md"
TOTAL_WEEKS = 10
BAR_WIDTH = 20
START, END = "<!-- progress:start -->", "<!-- progress:end -->"

WEEK_HEADER = re.compile(r"^## Week (\d+)\b", re.MULTILINE)
CHECKBOX = re.compile(r"^\s*- \[([ x~])\]", re.MULTILINE)


def bar(fraction: float, width: int = BAR_WIDTH) -> str:
    filled = int(round(fraction * width))
    return "`[" + "█" * filled + "░" * (width - filled) + "]`"


def week_scores(text: str) -> dict[int, tuple[float, int]]:
    """Map week number -> (done points, item count) for every ``## Week N`` section."""
    scores: dict[int, tuple[float, int]] = {}
    headers = list(WEEK_HEADER.finditer(text))
    for i, h in enumerate(headers):
        week = int(h.group(1))
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        # stop at the next level-2 header that is not a week (e.g. "## Weeks 4 to 10")
        nxt = re.search(r"^## ", text[h.end():end], re.MULTILINE)
        section = text[h.end(): h.end() + nxt.start()] if nxt else text[h.end():end]
        marks = CHECKBOX.findall(section)
        done = sum(1.0 if m == "x" else 0.5 if m == "~" else 0.0 for m in marks)
        scores[week] = (done, len(marks))
    return scores


def render(scores: dict[int, tuple[float, int]]) -> str:
    per_week = []
    for week in range(1, TOTAL_WEEKS + 1):
        done, n = scores.get(week, (0.0, 0))
        per_week.append(done / n if n else 0.0)
    overall = sum(per_week) / TOTAL_WEEKS
    started = [w for w in range(1, TOTAL_WEEKS + 1) if scores.get(w, (0, 0))[1]]
    scoped = sum(per_week[w - 1] for w in started) / len(started) if started else 0.0
    scope_label = f"Weeks {started[0]}-{started[-1]}" if started else "no week started"

    lines = [
        START,
        f"**Progress: {overall:.0%} of the 10-week plan** {bar(overall)} · "
        f"{scope_label} in progress: {scoped:.0%} {bar(scoped)}",
        "",
        "| Week | Items | Done | Progress | |",
        "| :--- | ---: | ---: | :--- | ---: |",
    ]
    for week in range(1, TOTAL_WEEKS + 1):
        done, n = scores.get(week, (0.0, 0))
        frac = per_week[week - 1]
        if n:
            lines.append(f"| Week {week} | {n} | {done:g} | {bar(frac)} | {frac:.0%} |")
        else:
            lines.append(f"| Week {week} | - | - | {bar(0.0)} | not started |")
    lines.append("")
    lines.append("_Generated by `scripts/roadmap_progress.py` from the checkboxes below; rerun it after ticking items._")
    lines.append(END)
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = ROADMAP.read_text(encoding="utf-8")
    if START not in text or END not in text:
        sys.exit(f"{ROADMAP}: markers {START} / {END} not found")
    block = render(week_scores(text))
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    new_text = head + block + tail
    if "--check" in argv:
        if new_text != text:
            print("ROADMAP.md progress block is out of date; run scripts/roadmap_progress.py")
            return 1
        print("ROADMAP.md progress block is up to date")
        return 0
    if new_text != text:
        ROADMAP.write_text(new_text, encoding="utf-8", newline="\n")
        print("ROADMAP.md progress block updated")
    else:
        print("ROADMAP.md progress block already current")
    # ASCII-only summary so it prints on a cp1252 Windows console
    summary = re.sub(r"`\[[^\]]*\]`", "", block.split("\n")[1]).replace("**", "")
    print(re.sub(r"\s+", " ", summary).strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
